[package]
name = "realtime-noise-tools"
version = "0.1.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
tract = ["realtime-noise-model/tract"]

[dependencies]
realtime-noise-model = { path = "../model", default-features = false }
serde_json = { version = "=1.0.145", default-features = false, features = ["std"] }
sha2 = { version = "=0.10.9", default-features = false, features = ["std"] }

[lints]
workspace = true
