#![forbid(unsafe_code)]
#![allow(clippy::doc_markdown)]

//! `OpenVINO` acceleration backend (Intel NPU, Intel GPU, CPU).
//!
//! # Wiring
//!
//! - **Detection**: [`OpenVINOBackend::is_available`] / [`OpenVINOBackend::available_devices`]
//!   probe the native runtime through `realtime-noise-runtime-openvino` (dynamic loading, so
//!   builds and hosts without OpenVINO are unaffected) and order the devices NPU, GPU, CPU.
//! - **Loading**: [`OpenVINOBackend::load_stateful`] compiles the three explicit-state
//!   DeepFilterNet3 graphs (`enc`, `erb_dec`, `df_dec`) for one device;
//!   [`OpenVINOBackend::load_stateful_auto`] walks the fallback order until one device works.
//! - **Precision**: the Clearcore policy lives in `realtime_noise_runtime_openvino::precision`
//!   (FP16 on NPU/GPU, FP32 on the x86 CPU baseline) and is applied through
//!   `INFERENCE_PRECISION_HINT` at compile time.
//! - **Processing**: the network is the neural half of DeepFilterNet3. STFT, ERB features,
//!   mask/deep filtering and iSTFT run in `realtime_noise_model::DspPipeline`; this module plugs
//!   the OpenVINO session into it as a [`SpectralModelBackend`].
//! - **Provenance**: the stateful graphs are derived from the approved asset but are not part of
//!   its signed archive, so [`OpenVINOBackend::load_stateful`] pins each file to a SHA-256
//!   ([`APPROVED_STATEFUL_DIGESTS`], mirrored in `models/stateful/README.md`) and fails closed on
//!   any mismatch. The verified bytes are the ones compiled; the files are never re-read.
//! - **Fallback**: a backend built with [`OpenVINOBackend::new`] (or any `new_mock*`) owns no
//!   native session and passes frames through, exactly like the earlier stub; check
//!   [`OpenVINOBackend::executes_inference`] before trusting it as real inference.

use std::fmt::Write as _;
use std::path::Path;

use deep_filter::Complex32;
use realtime_noise_contracts::AudioFrame;
use realtime_noise_model::{
    ALGORITHM_LATENCY_SAMPLES, AgnosticDspBackend, ApprovedAssetManifest, BackendDescriptor,
    DspPipelineConfig, ExtractedFeatures, InferenceBackend, InferenceError, ModelFrameOutput,
    ProcessedFrame, SpectralModelBackend,
};
use realtime_noise_runtime_openvino::dfn3::{
    DF_COEFS_LEN, DF_DEC_FILE, DF_ORDER, ENC_FILE, ERB_DEC_FILE, NB_DF,
};
use realtime_noise_runtime_openvino::{
    DeviceKind, Dfn3Graphs, Dfn3Output, Dfn3Session, InferencePrecision, OpenVinoError,
    fallback_order, precision_for_device,
};
use sha2::{Digest, Sha256};

const BACKEND_VERSION: &str = "2025.1.0";

/// Expected SHA-256 (lowercase hex) of each stateful DeepFilterNet3 graph.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StatefulDigests {
    pub enc: &'static str,
    pub erb_dec: &'static str,
    pub df_dec: &'static str,
}

/// Digests of the graphs in `models/stateful/`, generated by
/// `tools/accelerators/make_stateful_onnx.py` from `df-compatible-release-asset-v1`.
///
/// Changing a graph means regenerating it, updating `models/stateful/README.md` and these
/// constants together; a stale constant makes loading fail closed.
pub const APPROVED_STATEFUL_DIGESTS: StatefulDigests = StatefulDigests {
    enc: "c061d8a021d060f00a01a3191bf5a253247f359987b2a13043ef0ad46931191e",
    erb_dec: "0c84ecc2841445c0a4eee5486f43212bf41241a4459a887bf067a79cdeb057b4",
    df_dec: "a65a3dd9b763add2cfa7e822e7e910d0d70297426dff1b3863336a970b4ea655",
};

/// Lowercase hex SHA-256 of `bytes`.
#[must_use]
pub fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest {
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}

fn read_verified_file(
    model_dir: &Path,
    file: &str,
    expected: &str,
) -> Result<Vec<u8>, InferenceError> {
    let bytes = Dfn3Graphs::read_file(model_dir, file).map_err(|error| load_error(&error))?;
    let actual = sha256_hex(&bytes);
    if actual.eq_ignore_ascii_case(expected) {
        Ok(bytes)
    } else {
        Err(InferenceError::AssetNotApproved(format!(
            "{file}: SHA-256 {actual} does not match the expected {expected}"
        )))
    }
}

/// Reads the three graphs from `model_dir` and checks each against `digests`.
fn read_verified_graphs(
    model_dir: &Path,
    digests: &StatefulDigests,
) -> Result<Dfn3Graphs, InferenceError> {
    Ok(Dfn3Graphs {
        enc: read_verified_file(model_dir, ENC_FILE, digests.enc)?,
        erb_dec: read_verified_file(model_dir, ERB_DEC_FILE, digests.erb_dec)?,
        df_dec: read_verified_file(model_dir, DF_DEC_FILE, digests.df_dec)?,
    })
}

fn runtime_and_profile(device: &str) -> (&'static str, &'static str) {
    match DeviceKind::from_device_name(device) {
        DeviceKind::Gpu => ("openvino-gpu", "intel-gpu"),
        DeviceKind::Cpu => ("openvino-cpu", "intel-cpu"),
        DeviceKind::Npu | DeviceKind::Other => ("openvino-npu", "intel-npu"),
    }
}

fn descriptor_for(device: &str, asset_id: String, asset_sha256: String) -> BackendDescriptor {
    let (runtime, cpu_profile) = runtime_and_profile(device);
    BackendDescriptor {
        backend: "openvino",
        backend_version: BACKEND_VERSION,
        runtime,
        runtime_version: BACKEND_VERSION,
        asset_id,
        asset_sha256,
        cpu_profile,
    }
}

fn execution_error(error: &OpenVinoError) -> InferenceError {
    InferenceError::InferenceExecution(error.to_string())
}

fn load_error(error: &OpenVinoError) -> InferenceError {
    match error {
        OpenVinoError::ModelReadFailed(message) => InferenceError::ModelCorruption(message.clone()),
        other => InferenceError::InferenceExecution(other.to_string()),
    }
}

/// Adapter running a [`Dfn3Session`] as the neural stage of the shared DSP pipeline.
struct OpenVinoSpectralModel {
    session: Dfn3Session,
    descriptor: BackendDescriptor,
    scratch: Box<Dfn3Output>,
}

impl SpectralModelBackend for OpenVinoSpectralModel {
    fn descriptor(&self) -> BackendDescriptor {
        self.descriptor.clone()
    }

    fn process_spectrum(
        &mut self,
        features: &ExtractedFeatures,
    ) -> Result<ModelFrameOutput, InferenceError> {
        self.session
            .run_frame(&features.feat_erb, &features.feat_spec, &mut self.scratch)
            .map_err(|error| execution_error(&error))?;

        // `df_coefs` is `[bin][tap][re, im]` flattened.
        let df_coefs: Vec<[Complex32; DF_ORDER]> = self
            .scratch
            .df_coefs
            .chunks_exact(DF_COEFS_LEN / NB_DF)
            .map(|bin| std::array::from_fn(|tap| Complex32::new(bin[2 * tap], bin[2 * tap + 1])))
            .collect();

        Ok(ModelFrameOutput {
            lsnr: self.scratch.lsnr,
            erb_gains: Some(self.scratch.erb_mask),
            df_coefs: Some(df_coefs),
        })
    }

    fn reset(&mut self) -> Result<(), InferenceError> {
        self.session
            .reset()
            .map_err(|error| execution_error(&error))
    }
}

enum Engine {
    /// No native session: frames pass through unchanged (simulation / mock).
    Passthrough,
    /// Real OpenVINO inference inside the shared DSP pipeline.
    Neural(Box<AgnosticDspBackend<OpenVinoSpectralModel>>),
}

/// `OpenVINO` acceleration backend targeting Intel NPU, GPU (Arc / iGPU), or CPU devices.
pub struct OpenVINOBackend {
    descriptor: BackendDescriptor,
    device: String,
    engine: Engine,
    simulated_failure: bool,
}

impl std::fmt::Debug for OpenVINOBackend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("OpenVINOBackend")
            .field("descriptor", &self.descriptor)
            .field("device", &self.device)
            .field("hardware_accelerated", &self.is_hardware_accelerated())
            .field("simulated_failure", &self.simulated_failure)
            .finish_non_exhaustive()
    }
}

impl OpenVINOBackend {
    /// Creates a backend without a native session (frames pass through unchanged).
    ///
    /// Use [`Self::load_stateful`] for real inference.
    pub fn new(
        asset_id: impl Into<String>,
        asset_sha256: impl Into<String>,
        device: impl Into<String>,
    ) -> Self {
        let dev = device.into();
        Self {
            descriptor: descriptor_for(&dev, asset_id.into(), asset_sha256.into()),
            device: dev,
            engine: Engine::Passthrough,
            simulated_failure: false,
        }
    }

    /// Loads the stateful DeepFilterNet3 graphs from `model_dir` and compiles them for `device`
    /// (`"NPU"`, `"GPU"`, `"GPU.1"`, `"CPU"`, ...).
    ///
    /// `asset_id` / `asset_sha256` are recorded in the provenance of every frame. The graph files
    /// themselves must hash to [`APPROVED_STATEFUL_DIGESTS`]; otherwise this fails with
    /// [`InferenceError::AssetNotApproved`] before the native runtime is touched.
    pub fn load_stateful(
        model_dir: impl AsRef<Path>,
        device: &str,
        asset_id: impl Into<String>,
        asset_sha256: impl Into<String>,
    ) -> Result<Self, InferenceError> {
        Self::load_stateful_verified(
            model_dir,
            device,
            asset_id,
            asset_sha256,
            &APPROVED_STATEFUL_DIGESTS,
        )
    }

    /// [`Self::load_stateful`] against an explicit set of expected digests.
    ///
    /// Test hook: production code must use [`Self::load_stateful`], which pins the digests to
    /// [`APPROVED_STATEFUL_DIGESTS`]. Hidden from the docs because passing other digests defeats
    /// that pin.
    #[doc(hidden)]
    pub fn load_stateful_verified(
        model_dir: impl AsRef<Path>,
        device: &str,
        asset_id: impl Into<String>,
        asset_sha256: impl Into<String>,
        digests: &StatefulDigests,
    ) -> Result<Self, InferenceError> {
        let graphs = read_verified_graphs(model_dir.as_ref(), digests)?;
        let session =
            Dfn3Session::load_graphs(&graphs, device).map_err(|error| load_error(&error))?;
        Self::from_session(session, asset_id.into(), asset_sha256.into())
    }

    /// Tries `devices` in order and keeps the first that compiles. The graphs are verified once
    /// against [`APPROVED_STATEFUL_DIGESTS`].
    pub fn load_stateful_with_fallback(
        model_dir: impl AsRef<Path>,
        devices: &[String],
        asset_id: impl Into<String>,
        asset_sha256: impl Into<String>,
    ) -> Result<Self, InferenceError> {
        let graphs = read_verified_graphs(model_dir.as_ref(), &APPROVED_STATEFUL_DIGESTS)?;
        let session = Dfn3Session::load_graphs_with_fallback(&graphs, devices)
            .map_err(|error| load_error(&error))?;
        Self::from_session(session, asset_id.into(), asset_sha256.into())
    }

    /// Like [`Self::load_stateful_with_fallback`] over the devices OpenVINO reports on this host,
    /// in tier order: NPU, GPU, CPU.
    pub fn load_stateful_auto(
        model_dir: impl AsRef<Path>,
        asset_id: impl Into<String>,
        asset_sha256: impl Into<String>,
    ) -> Result<Self, InferenceError> {
        let devices = Self::available_devices();
        Self::load_stateful_with_fallback(model_dir, &devices, asset_id, asset_sha256)
    }

    fn from_session(
        session: Dfn3Session,
        asset_id: String,
        asset_sha256: String,
    ) -> Result<Self, InferenceError> {
        let device = session.device().to_owned();
        let descriptor = descriptor_for(&device, asset_id, asset_sha256);
        let model = OpenVinoSpectralModel {
            session,
            descriptor: descriptor.clone(),
            scratch: Box::new(Dfn3Output::new()),
        };
        let pipeline = AgnosticDspBackend::new(model, DspPipelineConfig::default())?;
        Ok(Self {
            descriptor,
            device,
            engine: Engine::Neural(Box::new(pipeline)),
            simulated_failure: false,
        })
    }

    #[must_use]
    pub fn from_manifest(manifest: &ApprovedAssetManifest) -> Self {
        Self::new(manifest.asset_id(), manifest.asset_sha256(), "NPU")
    }

    #[must_use]
    pub fn new_mock() -> Self {
        Self::new("df-compatible-release-asset-v1", "mock-asset-sha256", "NPU")
    }

    #[must_use]
    pub fn new_mock_npu() -> Self {
        Self::new("df-compatible-release-asset-v1", "mock-asset-sha256", "NPU")
    }

    #[must_use]
    pub fn new_mock_gpu() -> Self {
        Self::new("df-compatible-release-asset-v1", "mock-asset-sha256", "GPU")
    }

    #[must_use]
    pub fn new_mock_cpu() -> Self {
        Self::new("df-compatible-release-asset-v1", "mock-asset-sha256", "CPU")
    }

    /// Whether the native OpenVINO runtime can be loaded on this host.
    #[must_use]
    pub fn is_available() -> bool {
        realtime_noise_runtime_openvino::is_openvino_available()
    }

    /// Devices OpenVINO reports on this host that Clearcore drives, in tier order
    /// (NPU, GPU, CPU). Empty when the runtime is not installed.
    #[must_use]
    pub fn available_devices() -> Vec<String> {
        fallback_order(&realtime_noise_runtime_openvino::available_devices())
    }

    /// Version string reported by the loaded native runtime, if any.
    #[must_use]
    pub fn native_runtime_version() -> Option<String> {
        realtime_noise_runtime_openvino::openvino_version()
    }

    #[must_use]
    pub fn device(&self) -> &str {
        &self.device
    }

    /// Precision the policy requests for this backend's device.
    #[must_use]
    pub fn precision(&self) -> InferencePrecision {
        precision_for_device(&self.device)
    }

    /// True when frames go through a compiled OpenVINO network; false for the passthrough stub.
    #[must_use]
    pub const fn executes_inference(&self) -> bool {
        matches!(self.engine, Engine::Neural(_))
    }

    /// Alias of [`Self::executes_inference`], kept for existing callers.
    #[must_use]
    pub const fn is_hardware_accelerated(&self) -> bool {
        self.executes_inference()
    }

    pub const fn set_simulated_failure(&mut self, fail: bool) {
        self.simulated_failure = fail;
    }

    /// Clears the recurrent state of the network and the DSP pipeline. No-op for the stub.
    pub fn reset(&mut self) -> Result<(), InferenceError> {
        match &mut self.engine {
            Engine::Passthrough => Ok(()),
            Engine::Neural(pipeline) => pipeline.reset(),
        }
    }
}

impl InferenceBackend for OpenVINOBackend {
    fn descriptor(&self) -> BackendDescriptor {
        self.descriptor.clone()
    }

    fn process(&mut self, input: &AudioFrame) -> Result<ProcessedFrame, InferenceError> {
        if self.simulated_failure {
            return Err(InferenceError::InferenceExecution(
                "OpenVINO hardware execution failed".to_owned(),
            ));
        }

        if input.iter().any(|sample| !sample.is_finite()) {
            return Err(InferenceError::InputContract(
                "input frame contains a non-finite sample".to_owned(),
            ));
        }

        match &mut self.engine {
            Engine::Passthrough => {
                ProcessedFrame::checked(*input, ALGORITHM_LATENCY_SAMPLES, self.descriptor.clone())
            }
            Engine::Neural(pipeline) => match pipeline.process(input) {
                Ok(frame) => Ok(frame),
                Err(error) => {
                    // A failed hop leaves the recurrent state half-advanced; start clean so the
                    // caller can fall back (or retry) without replaying a corrupted history.
                    let _ = pipeline.reset();
                    Err(error)
                }
            },
        }
    }

    fn algorithmic_latency_samples(&self) -> u32 {
        ALGORITHM_LATENCY_SAMPLES
    }
}
