[package]
name = "literal-member"
version = "0.0.0"
edition = "2024"

[features]
'default' = [ ]

[dependencies]
"shared#dependency" = { workspace = true }
'path-shared' = { workspace = true }

[dev-dependencies]
dev-ok = { version = "1", default-features = false }

[build-dependencies]
build-ok = {
    version = "1",
    "default-features" = false,
}
